import { Platform, StyleSheet } from 'react-native';
import { colors, radii, spacing, typography } from './theme';

export const appStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface },
  app: { flex: 1 },
  flex: { flex: 1 },
  desktopSafe: { backgroundColor: colors.surfaceMuted },
  desktopApp: { flexDirection: 'row' },
  desktopMain: { flex: 1, minWidth: 0 },
  desktopSidebar: {
    width: 236,
    paddingHorizontal: 18,
    paddingTop: 28,
    paddingBottom: 24,
    backgroundColor: colors.surface,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: colors.separator,
    justifyContent: 'space-between',
  },
  desktopBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 10,
    marginBottom: 38,
  },
  desktopBrandMark: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brand,
  },
  desktopBrand: { color: colors.ink, fontSize: 24, fontWeight: '700', letterSpacing: -0.6 },
  desktopNav: { flex: 1, gap: 6 },
  desktopNavItem: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    paddingHorizontal: 13,
    borderRadius: 14,
  },
  desktopNavItemActive: { backgroundColor: colors.brandSoft },
  desktopNavLabel: { color: colors.secondary, fontSize: 15, fontWeight: '600' },
  desktopNavLabelActive: { color: colors.brandDeep },
  desktopSidebarFooter: { gap: 14 },
  desktopCreateButton: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.ink,
  },
  desktopCreateLabel: { color: colors.surface, fontSize: 15, fontWeight: '700' },
  desktopFooterCopy: { color: colors.tertiary, fontSize: 12, lineHeight: 17, paddingHorizontal: 6 },
  dashboardPage: { flexGrow: 1, paddingHorizontal: 42, paddingTop: 34, paddingBottom: 48 },
  dashboardHeading: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 28,
  },
  dashboardEyebrow: {
    color: colors.brandDeep,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.3,
    marginBottom: 6,
  },
  dashboardDate: { color: colors.secondary, fontSize: 14, paddingBottom: 4 },
  dashboardGrid: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'flex-start', gap: 22 },
  dashboardCard: {
    minHeight: 286,
    flexGrow: 1,
    flexBasis: 420,
    maxWidth: 660,
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: colors.surface,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 18,
    elevation: 2,
  },
  receiptsCard: { minHeight: 330 },
  dashboardCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  dashboardCardTitle: {
    color: colors.ink,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  dashboardCardSub: { color: colors.secondary, fontSize: 14, marginTop: 3 },
  dashboardCardIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandSoft,
  },
  dashboardCardBody: { flex: 1 },
  dashboardListRow: { minHeight: 66, paddingVertical: 12 },
  dashboardRowTitle: { fontSize: 16, lineHeight: 21 },
  dashboardRowSub: { fontSize: 13, lineHeight: 18 },
  dashboardRowValue: { fontSize: 15, lineHeight: 20 },
  dashboardCardAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    alignSelf: 'flex-start',
    marginTop: 14,
  },
  dashboardCardActionLabel: { color: colors.brandDeep, fontSize: 14, fontWeight: '700' },
  dashboardEmpty: { color: colors.secondary, paddingVertical: 20, ...typography.subheadline },
  dashboardCardPlaceholder: {
    minHeight: 286,
    flexGrow: 1,
    flexBasis: 260,
    maxWidth: 360,
    alignItems: 'flex-start',
    justifyContent: 'center',
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: 'rgba(255,255,255,0.66)',
  },
  dashboardPlaceholderTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '700',
    marginTop: 15,
    marginBottom: 5,
  },
  dashboardPlaceholderCopy: {
    color: colors.secondary,
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 220,
  },
  page: { paddingHorizontal: spacing.lg, paddingTop: spacing.xl, paddingBottom: 130 },
  authScreen: { flex: 1, backgroundColor: colors.surfaceMuted },
  authShell: { flex: 1, backgroundColor: colors.surface },
  authShellDesktop: {
    flexDirection: 'row',
    width: '100%',
    overflow: 'hidden',
  },
  authMain: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 28,
    paddingVertical: 28,
    justifyContent: 'space-between',
  },
  authBrandRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  authBrandMark: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brand,
  },
  authBrand: { color: colors.ink, fontSize: 24, fontWeight: '700', letterSpacing: -0.6 },
  authContent: { width: '100%', maxWidth: 430, alignSelf: 'center', alignItems: 'center', gap: 14 },
  authTitle: {
    color: colors.ink,
    textAlign: 'center',
    fontSize: 38,
    lineHeight: 45,
    fontWeight: '700',
    letterSpacing: -1,
  },
  authSubtitle: {
    color: colors.secondary,
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 23,
    marginBottom: 18,
  },
  googleButton: {
    width: '100%',
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D9DDD9',
    backgroundColor: colors.surface,
    ...(Platform.OS === 'web' ? { boxShadow: '0 3px 7px rgba(17, 17, 17, 0.06)' } : {}),
  },
  googleButtonPressed: { backgroundColor: colors.surfaceMuted, opacity: 0.78 },
  googleButtonLabel: { color: colors.ink, fontSize: 16, lineHeight: 22, fontWeight: '600' },
  authTerms: {
    color: colors.secondary,
    alignSelf: 'center',
    maxWidth: 400,
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 18,
  },
  authTermsLink: { color: colors.ink, textDecorationLine: 'underline' },
  authVisual: {
    flex: 0.82,
    minWidth: 360,
    justifyContent: 'flex-end',
    padding: 34,
    backgroundColor: colors.brandDeep,
  },
  authVisualImage: { opacity: 0.92 },
  authVisualCopy: {
    maxWidth: 310,
    padding: 20,
    borderRadius: 18,
    backgroundColor: 'rgba(17, 17, 17, 0.56)',
  },
  authVisualEyebrow: {
    color: colors.brand,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  authVisualTitle: {
    color: colors.surface,
    fontSize: 28,
    lineHeight: 33,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  welcome: { flex: 1, backgroundColor: colors.brand, padding: spacing.lg },
  welcomeCenter: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 20 },
  logoCircle: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeTitle: { color: '#FFFFFF', ...typography.display },
  welcomeCopy: {
    maxWidth: 360,
    textAlign: 'center',
    color: 'rgba(255,255,255,0.9)',
    fontSize: 20,
    lineHeight: 29,
    fontWeight: '400',
  },
  welcomeActions: { gap: 22, paddingBottom: 20 },
  demoLink: { color: '#FFFFFF', textAlign: 'center', ...typography.headline },
  authError: { color: '#FFE4E1', textAlign: 'center', ...typography.subheadline },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  pageTitle: { color: colors.ink, ...typography.screenTitle },
  sectionTitle: { color: colors.ink, marginTop: 8, ...typography.sectionTitle },
  homeSectionTitle: { marginTop: spacing.xxl, marginBottom: spacing.sm },
  hero: {
    marginVertical: 28,
    backgroundColor: colors.brand,
    borderRadius: radii.xl,
    padding: 26,
    gap: 8,
  },
  detailHero: {
    backgroundColor: 'rgba(112, 207, 69, 0.94)',
    paddingHorizontal: spacing.lg,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  detailHeroCopy: { flex: 1, minWidth: 0, gap: 4 },
  heroEyebrow: { color: 'rgba(255,255,255,0.86)', ...typography.caption, letterSpacing: 1.1 },
  heroAmount: { color: '#FFFFFF', ...typography.amount },
  heroCopy: { flex: 1, color: 'rgba(255,255,255,0.88)', ...typography.subheadline },
  heroPeopleAction: { minHeight: 28, alignSelf: 'flex-start', justifyContent: 'center' },
  heroPeopleGroup: { flexDirection: 'row', alignItems: 'center', paddingLeft: 2 },
  heroPeopleAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1.5,
    borderColor: 'rgba(47,133,21,0.35)',
  },
  heroPeopleAvatarOverlap: { marginLeft: -7 },
  heroPeopleInitial: { color: colors.brandDeep, fontSize: 10, fontWeight: '700' },
  heroQrAction: {
    width: 96,
    alignItems: 'center',
    gap: 4,
  },
  heroQrCard: {
    padding: 6,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
  },
  heroQrLabel: { color: colors.surface, ...typography.caption },
  detailScrollContent: { paddingBottom: spacing.lg },
  listRow: {
    minHeight: 86,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
    paddingVertical: 18,
  },
  marker: { width: 9, height: 54, borderRadius: 5 },
  rowCopy: { flex: 1, gap: 4 },
  rowTitle: { color: colors.ink, ...typography.title },
  rowSub: { color: colors.secondary, ...typography.subheadline },
  rowValue: { color: colors.ink, ...typography.headline },
  warningText: { color: colors.warning },
  tabBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 92,
    backgroundColor: '#FFFFFF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.separator,
    flexDirection: 'row',
    paddingHorizontal: 6,
    paddingBottom: 8,
  },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 5 },
  tabLabel: { color: colors.tertiary, fontSize: 10, fontWeight: '700' },
  tabActive: { color: colors.ink },
  createTab: { flex: 1.25, alignItems: 'center', top: -18, gap: 4 },
  createButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 5,
    borderColor: '#FFFFFF',
  },
  header: {
    minHeight: 58,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  headerTitle: { maxWidth: '72%', color: colors.ink, ...typography.headline },
  centerPage: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28, gap: 22 },
  invitePage: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 34,
    gap: 18,
  },
  centerCopy: { color: colors.secondary, textAlign: 'center', ...typography.body },
  bottomActions: { alignSelf: 'stretch', gap: 20, marginTop: 'auto', paddingBottom: 18 },
  secondaryLink: { color: colors.ink, textAlign: 'center', padding: 12, ...typography.headline },
  tertiaryLink: {
    color: colors.secondary,
    textAlign: 'center',
    padding: 8,
    ...typography.subheadline,
  },
  captureError: {
    color: colors.negative,
    textAlign: 'center',
    borderRadius: radii.sm,
    backgroundColor: colors.negativeSoft,
    padding: spacing.md,
    ...typography.subheadline,
  },
  receiptConfirmPage: { flex: 1, padding: spacing.lg, gap: spacing.lg },
  receiptConfirmImage: {
    flex: 1,
    width: '100%',
    minHeight: 280,
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceMuted,
  },
  receiptConfirmCopy: { alignItems: 'center', gap: spacing.sm },
  receiptPeekButton: {
    position: 'absolute',
    right: 16,
    bottom: 140,
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.brand,
    backgroundColor: colors.surface,
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 3,
  },
  receiptPeekButtonPressed: { backgroundColor: colors.brandSoft },
  receiptPeekOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    backgroundColor: 'rgba(16, 22, 18, 0.72)',
  },
  receiptPeekImageFrame: {
    width: '100%',
    height: '84%',
    maxWidth: 430,
    borderRadius: radii.lg,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  receiptPeekImage: { width: '100%', height: '100%' },
  scanNotice: {
    color: colors.ink,
    borderRadius: radii.sm,
    backgroundColor: colors.brandSoft,
    padding: spacing.md,
    marginBottom: spacing.sm,
    ...typography.subheadline,
  },
  nameInput: {
    color: colors.ink,
    borderBottomWidth: 1,
    borderBottomColor: colors.separator,
    paddingVertical: 16,
    ...typography.sectionTitle,
  },
  peopleSection: { alignSelf: 'stretch', gap: 14, marginTop: 4 },
  peopleSectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  peopleHeaderAction: {
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 28,
    backgroundColor: colors.brandSoft,
  },
  peopleRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    columnGap: 14,
    rowGap: 16,
    alignSelf: 'stretch',
    paddingVertical: 4,
  },
  peoplePerson: { width: 70, alignItems: 'center', gap: 4 },
  peopleAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandSoft,
  },
  peopleAvatarInitial: { color: colors.brandDeep, ...typography.headline },
  peopleName: { width: 70, color: colors.ink, ...typography.caption, textAlign: 'center' },
  peopleSource: {
    width: 70,
    color: colors.secondary,
    fontSize: 10,
    lineHeight: 12,
    textAlign: 'center',
  },
  addPersonForm: {
    alignSelf: 'stretch',
    gap: 10,
    padding: 16,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
  },
  personInput: {
    minHeight: 48,
    color: colors.ink,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.separator,
    borderRadius: radii.sm,
    paddingHorizontal: 14,
    ...typography.body,
  },
  formHint: { color: colors.secondary, ...typography.subheadline },
  receiptInstructions: {
    color: colors.secondary,
    marginTop: spacing.sm,
    ...typography.body,
  },
  receiptItemsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  receiptItemsTitle: { color: colors.ink, ...typography.title },
  addItemButton: {
    minHeight: 40,
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: 12,
    borderRadius: radii.pill,
    backgroundColor: colors.brandSoft,
    marginTop: spacing.md,
  },
  addItemLabel: { color: colors.brandDeep, ...typography.headline },
  emptyItems: {
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.xl,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
  },
  emptyItemsTitle: { color: colors.ink, ...typography.headline },
  receiptItemRow: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
    paddingVertical: 14,
  },
  swipeableItem: { position: 'relative', overflow: 'hidden' },
  swipeableItemContent: { backgroundColor: colors.surface },
  swipeDeleteAction: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 92,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    backgroundColor: colors.negative,
  },
  swipeDeleteLabel: { color: colors.surface, ...typography.caption },
  quantityBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.separator,
  },
  quantityBadgeText: { color: colors.ink, ...typography.headline },
  itemNameTarget: { flex: 1, justifyContent: 'center', minWidth: 0 },
  itemPriceTarget: { justifyContent: 'center', minWidth: 64, alignItems: 'flex-end' },
  itemEditor: {
    gap: 10,
    padding: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: colors.surfaceMuted,
    marginVertical: spacing.sm,
  },
  itemEditorHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  itemEditorTitle: { color: colors.ink, marginBottom: 2, ...typography.title },
  itemEditorDeleteButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: colors.negativeSoft,
  },
  inputLabel: { color: colors.ink, ...typography.subheadline, fontWeight: '600' },
  itemInput: {
    minHeight: 52,
    color: colors.ink,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.separator,
    borderRadius: radii.sm,
    paddingHorizontal: 14,
    ...typography.body,
  },
  itemInputRow: { flexDirection: 'row', gap: 12 },
  quantityField: { width: 110, gap: 8 },
  priceField: { flex: 1, gap: 8 },
  priceInputShell: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.separator,
    borderRadius: radii.sm,
    paddingHorizontal: 14,
  },
  currencyPrefix: { color: colors.secondary, marginRight: 6, ...typography.body },
  priceInput: { flex: 1, color: colors.ink, paddingVertical: 0, ...typography.body },
  itemError: { color: colors.negative, ...typography.subheadline },
  itemEditorActions: { flexDirection: 'row', gap: 12, marginTop: spacing.sm },
  cancelItemButton: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: colors.separator,
  },
  cancelItemLabel: { color: colors.ink, ...typography.headline },
  saveItemButton: {
    flex: 1,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: colors.brand,
  },
  saveItemLabel: { color: colors.surface, ...typography.headline },
  totalBlock: {
    backgroundColor: colors.surfaceMuted,
    borderRadius: radii.md,
    padding: 18,
    marginVertical: 20,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 7,
  },
  editableTotalRow: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  editableTotalLabel: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: spacing.sm,
  },
  taxTipLabel: { color: colors.ink, ...typography.subheadline, fontWeight: '600' },
  taxTipPercentage: { color: colors.tertiary, ...typography.caption, fontWeight: '600' },
  totalInputShell: {
    width: 126,
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: colors.surface,
    paddingHorizontal: 11,
  },
  totalInputPrefix: { color: colors.secondary, ...typography.headline },
  totalInput: {
    flex: 1,
    minWidth: 0,
    color: colors.ink,
    textAlign: 'right',
    paddingVertical: 0,
    ...typography.headline,
  },
  namedAdjustmentRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  adjustmentNameInput: {
    flex: 1,
    minWidth: 0,
    minHeight: 42,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.separator,
    backgroundColor: colors.surface,
    color: colors.ink,
    paddingHorizontal: 11,
    paddingVertical: 0,
    ...typography.subheadline,
  },
  namedAdjustmentAmount: { width: 116 },
  removeAdjustmentButton: {
    width: 36,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
  },
  adjustmentActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  adjustmentButton: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 11,
    borderRadius: radii.pill,
    backgroundColor: colors.brandSoft,
  },
  negativeAdjustmentButton: { backgroundColor: colors.negativeSoft },
  adjustmentButtonLabel: { color: colors.brandDeep, ...typography.subheadline, fontWeight: '600' },
  negativeAdjustmentButtonLabel: { color: colors.negative },
  warning: { color: colors.warning, marginBottom: 18, ...typography.headline },
  listSection: { paddingHorizontal: 24 },
  claimItem: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  claimItemSummary: {
    minHeight: 86,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
  },
  claimItemDisclosure: {
    flex: 1,
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  claimantPanel: {
    gap: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.md,
    marginBottom: spacing.md,
  },
  claimantPanelTitle: { color: colors.ink, ...typography.headline },
  participantRail: { gap: 12, paddingVertical: 12, paddingHorizontal: 2 },
  participantChoice: { width: 66, alignItems: 'center', gap: 5 },
  participantChoiceAdd: {
    width: 42,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  participantChoiceCircle: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 24,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.separator,
  },
  participantChoiceSelected: {
    backgroundColor: colors.brandSoft,
    borderColor: colors.brand,
  },
  participantChoiceInitial: { color: colors.secondary, ...typography.headline },
  participantChoiceLabel: { color: colors.secondary, ...typography.caption },
  participantChoiceLabelSelected: { color: colors.brandDeep },
  claimantRow: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 10 },
  claimantAvatar: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: colors.brandSoft,
  },
  claimantInitial: { color: colors.brandDeep, ...typography.caption },
  finalizeSection: {
    padding: spacing.lg,
    gap: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.separator,
    backgroundColor: 'rgba(255, 255, 255, 0.68)',
    shadowColor: colors.ink,
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 4,
  },
  ctaRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  ctaButtonFlex: { flex: 1 },
  saveProgressButton: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.ink,
  },
  finalizeHint: { color: colors.secondary, textAlign: 'center', ...typography.subheadline },
  summaryPage: { paddingBottom: spacing.xxl },
  summaryHero: {
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    backgroundColor: colors.brand,
  },
  summaryEyebrow: { color: 'rgba(255,255,255,0.86)', ...typography.headline },
  summaryAmount: { color: colors.surface, ...typography.amount },
  summaryCopy: { color: 'rgba(255,255,255,0.88)', ...typography.body },
  allocation: { padding: 24, gap: 18 },
  allocationItem: {
    gap: 12,
    paddingBottom: 22,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.separator,
  },
  allocationHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  allocationAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brandSoft,
  },
  allocationAvatarInitial: { color: colors.brandDeep, ...typography.headline },
  noItemsHelper: { color: colors.secondary, marginLeft: 58, ...typography.subheadline },
  allocationDetails: {
    gap: 12,
    padding: 14,
    borderRadius: radii.md,
    backgroundColor: colors.surfaceMuted,
  },
  allocationLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  paymentActions: { flexDirection: 'row', gap: 8, marginTop: 4 },
  paymentButton: {
    flex: 1,
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: radii.pill,
    paddingHorizontal: 8,
  },
  venmoButton: { backgroundColor: colors.venmoBlue },
  appleButton: { backgroundColor: colors.appleBlack },
  paymentButtonLabel: { color: '#FFFFFF', ...typography.headline },
  secondaryActionButton: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radii.pill,
    backgroundColor: colors.brandSoft,
    paddingHorizontal: 16,
  },
  secondaryActionLabel: { color: colors.brandDeep, ...typography.headline },
  qr: {
    maxWidth: '100%',
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: radii.lg,
  },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.4)' },
  inlineModalBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  modalDismissArea: { flex: 1 },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    padding: 28,
    gap: 18,
  },
  fallbackAmount: { color: colors.ink, textAlign: 'center', ...typography.amount },
  profileAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    overflow: 'hidden',
    backgroundColor: colors.brand,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 24,
  },
  profileInitial: { color: '#FFFFFF', ...typography.screenTitle },
  profileAvatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: 44,
  },
  signOut: { color: colors.negative, marginTop: 28, ...typography.headline },
});
